# Generated by Django 4.2.30 on 2026-04-23 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("genres", models.CharField(max_length=100)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("pc", "PC"),
                            ("ps4", "PlayStation 4"),
                            ("ps5", "PlayStation 5"),
                            ("xbox-one", "Xbox One"),
                            ("xbox-series", "Xbox Series X/S"),
                            ("switch", "Nintendo Switch"),
                            ("mobile", "Mobile"),
                        ],
                        max_length=20,
                    ),
                ),
                ("developer", models.CharField(blank=True, max_length=200)),
                ("publisher", models.CharField(blank=True, max_length=200)),
                ("release_year", models.IntegerField()),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0, max_digits=3),
                ),
                (
                    "user_rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completado"),
                            ("playing", "Jogando"),
                            ("wishlist", "Quero Jogar"),
                            ("dropped", "Abandonei"),
                        ],
                        default="wishlist",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0, help_text="Progresso em porcentagem (0-100)"
                    ),
                ),
                (
                    "hours_played",
                    models.IntegerField(default=0, help_text="Horas jogadas"),
                ),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("cover_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Games",
                "ordering": ["-created_at"],
            },
        ),
    ]
