# Generated by Django 4.2.30 on 2026-04-23 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("genres", models.CharField(max_length=100)),
                ("release_year", models.IntegerField()),
                ("director", models.CharField(blank=True, max_length=200)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0, max_digits=3),
                ),
                (
                    "user_rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("watched", "Assistido"),
                            ("watching", "Assistindo"),
                            ("wishlist", "Quero Assistir"),
                            ("dropped", "Abandonei"),
                        ],
                        default="wishlist",
                        max_length=20,
                    ),
                ),
                ("watched_date", models.DateField(blank=True, null=True)),
                ("poster_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Movies",
                "ordering": ["-created_at"],
            },
        ),
    ]
